services:
  api1:
    image: joaovitorgirardiii/rinha-2026-rust:test
    cpuset: "0"
    environment:
      PORT: "3000"
      INDEX_PATH: "/app/ivf_index.bin"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167MB"

  api2:
    image: joaovitorgirardiii/rinha-2026-rust:test
    cpuset: "1"
    environment:
      PORT: "3000"
      INDEX_PATH: "/app/ivf_index.bin"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167MB"

  haproxy:
    image: haproxy:2.8-alpine
    cpuset: "2"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "16MB"

networks:
  rinha:
    driver: bridge
